before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: DPAsgbuLubvGcUofndgxMFoAIVFPmyzWyBTvmHE9w2XYPiXXY4tKOnqz6B7eZnuDbrFsH80XqPhckC4VixaVylldYZv93Ui+rqqSHyp2mynmzfIB80Iankt+bZlQD67LwoPgwASoP4FjKEInGSmE696/XUSwBQthrctTToBkdo3K9BoHPv/zP22Fd5px58PxzUuuTUfG41P/0CIZCSKM5EHHc5Pxf1PP+s4l7zScwyCU7v0byc6iZbPtq3xxfq7A9xE/kTRvRPIqWO6F2coc9q8hbhAdYl1a8T5AiE6X0M34l1WXfFSwJ8ZNj6x+t5DK3lHCbyLuCn56KR3oFizQ+5e4PBZnL3LTcFgoXbU8dcGgAQqIuo7nVtb1WNT/Sx37AgVra0hV8CXejV5Hl+rqcwdrGf8sq2KKv+J8tIvsUkRaHRRv7pcsGQMLJVk3rB0vd+S+JywmnX+XZ/vNicXQZX2hREvuC9IFvTpCuIAqN7J7E5JWTRlCJXFmmW7jbVyzM9n63mh8h5AEo7MK652rbAxaQrHOqWF6UFmFub5nEjJ5YQ89NHXAmch7wA8hLiDXa4mOTlX6NTshOQj+F0ipnPjT6Mu5ghX+wztUHNJhpyhVR0llbEi4HxXjzdpqp3yE8m7zbog4xMmLAzM9I7KGSXjPQMASVkyJJBSJaESBadI= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
